local M = {}

M.options = {
  transparent = false,
}

local colors = {
  bg = "#181a1d",
  fg = "#bcbec4",
  bg_alt = "#161619",
  fg_dim = "#7a7e85",
  string = "#6aab73",
  string_alt = "#81CA91",
  keyword = "#ba8ef7",
  func = "#cf8e6d",
  number = "#56a8f5",
  comment = "#7F838C",
  shebang = "#ff8ad1",
  variable = "#14b8a6",
  constant = "#ffa763",
  operator = "#14b8a6",
  git_add = "#6A9955",
  git_del = "#f85149",
  git_mod = "#336ff1",
  error = "#f85149",
  warning = "#ff8a00",
  info = "#336ff1",
  hint = "#7a7e85",
  cursor_bg = "#ffffff",
  selection = "#373b39",
  line_highlight = "#252629",
  float_bg = "#161619",
  inserted = "#C3E88D",
  changed = "#C792EA",
  html_tag = "#f85149",
  jsx_component = "#ba8ef7",
  directory = "#56a8f5",
  search_match = "#ffb347",
}

function M.setup(opts)
  opts = vim.tbl_deep_extend("force", {
    transparent = vim.g.transparent_enabled or false,
  }, opts or {})
  M.options = opts
  return M
end

function M.load()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
  vim.g.colors_name = "atomizer"

  local highlights = {
    Normal = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    NormalNC = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    NormalFloat = { fg = colors.fg, bg = M.options.transparent and "none" or colors.float_bg },
    NormalSB = { fg = colors.fg, bg = colors.float_bg },
    CursorLine = { bg = colors.line_highlight },
    CursorLineNr = { fg = "#a1a3ab" },
    LineNr = { fg = "#4e5157" },
    Cursor = { fg = colors.bg, bg = colors.cursor_bg },
    lCursor = { fg = colors.bg, bg = colors.cursor_bg },
    CursorIM = { fg = colors.bg, bg = colors.cursor_bg },
    CursorColumn = { bg = colors.line_highlight },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.selection },
    SignColumn = { bg = M.options.transparent and "none" or colors.bg },
    SignColumnSB = { bg = colors.float_bg, fg = colors.fg_dim },
    Folded = { fg = colors.info, bg = M.options.transparent and "none" or colors.line_highlight },
    FoldColumn = { fg = colors.fg_dim },
    DiffAdd = { fg = colors.git_add },
    DiffChange = { fg = colors.git_mod },
    DiffDelete = { fg = colors.git_del },
    DiffText = { fg = colors.git_mod, bg = "#25324d" },
    Directory = { fg = colors.directory },
    IncSearch = { bg = "#505050", fg = colors.fg },
    CurSearch = { bg = colors.search_match, fg = "#ffffff" },
    Search = { bg = "#32593d", fg = colors.fg },
    MatchParen = { fg = "#ffb347", bg = "#3c3f41", bold = true },
    ModeMsg = { fg = colors.fg, bold = true },
    MoreMsg = { fg = colors.info },
    Question = { fg = colors.info },
    WarningMsg = { fg = colors.warning },
    ErrorMsg = { fg = colors.error, bold = true },
    NonText = { fg = colors.fg_dim },
    Whitespace = { fg = "#3c3f41" },
    SpecialKey = { fg = colors.fg_dim },
    Pmenu = { fg = colors.fg, bg = M.options.transparent and "none" or colors.float_bg },
    PmenuSel = { bg = "#25324d", bold = true },
    PmenuSbar = { bg = "#3c3f41" },
    PmenuThumb = { bg = colors.fg_dim },
    PmenuExtra = { fg = colors.fg_dim },
    PmenuExtraSel = { bg = "#25324d", bold = true },
    WildMenu = { bg = colors.fg_dim },
    StatusLine = { fg = colors.fg_dim, bg = M.options.transparent and "none" or colors.bg },
    StatusLineNC = { fg = colors.fg_dim, bg = M.options.transparent and "none" or colors.bg },
    TabLine = { bg = colors.bg_alt, fg = colors.fg_dim },
    TabLineSel = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    TabLineFill = { bg = M.options.transparent and "none" or colors.bg },
    TabLineNC = { bg = colors.bg_alt, fg = colors.fg_dim },
    WinBar = { fg = colors.fg },
    WinBarNC = { fg = colors.fg_dim },
    WinSeparator = { fg = M.options.transparent and "#3c3f41" or "#25262a" },
    FloatBorder = { fg = "#3c3f41" },
    FloatTitle = { fg = colors.fg, bg = M.options.transparent and "none" or "#25262a" },
    ColorColumn = { bg = "#252629" },
    Conceal = { fg = colors.fg_dim },
    EndOfBuffer = { fg = colors.fg_dim },
    QuickFixLine = { bg = "#3c3f41", bold = true },
    Substitute = { bg = "#3c3f41", fg = "#f85149" },
    SpellBad = { sp = colors.error, undercurl = true },
    SpellCap = { sp = colors.warning, undercurl = true },
    SpellLocal = { sp = colors.info, undercurl = true },
    SpellRare = { sp = "#6A9955", undercurl = true },
    ["@string"] = { fg = colors.string },
    ["@string.regex"] = { fg = "#56adb7" },
    ["@string.escape"] = { fg = colors.number },
    ["@string.special"] = { fg = colors.interpolation },
    ["@string.special.path"] = { fg = "#56a8f5", underline = true },
    ["@string.special.symbol"] = { fg = colors.string_alt },
    ["@string.special.url"] = { fg = "#56a8f5", underline = true },
    ["@character"] = { fg = colors.number },
    ["@character.special"] = { fg = colors.number },
    ["@number"] = { fg = colors.number },
    ["@boolean"] = { fg = "#f43f5e" },
    ["@number.float"] = { fg = colors.number },
    ["@float"] = { fg = colors.number },
    ["@keyword"] = { fg = colors.keyword },
    ["@keyword.function"] = { fg = colors.keyword },
    ["@keyword.operator"] = { fg = colors.keyword },
    ["@keyword.return"] = { fg = colors.keyword },
    ["@keyword.coroutine"] = { fg = colors.keyword },
    ["@keyword.conditional"] = { fg = colors.keyword },
    ["@keyword.repeat"] = { fg = colors.keyword },
    ["@keyword.exception"] = { fg = colors.keyword },
    ["@keyword.import"] = { fg = colors.keyword },
    ["@keyword.storage"] = { fg = colors.keyword },
    ["@keyword.directive"] = { fg = colors.keyword },
    ["@function"] = { fg = colors.func },
    ["@function.builtin"] = { fg = "#cf8e6d" },
    ["@function.call"] = { fg = colors.func },
    ["@function.macro"] = { fg = "#cf8e6d" },
    ["@function.method"] = { fg = colors.func },
    ["@function.method.call"] = { fg = colors.func },
    ["@constructor"] = { fg = "#ba8ef7" },
    ["@function.annotation"] = { fg = "#56a8f5" },
    ["@function.arrow"] = { fg = colors.variable },
    ["@function.return"] = { fg = colors.func },
    ["@operator"] = { fg = colors.operator },
    ["@parameter"] = { fg = colors.variable },
    ["@parameter.reference"] = { fg = colors.variable },
    ["@variable"] = { fg = colors.variable },
    ["@variable.builtin"] = { fg = colors.keyword },
    ["@variable.member"] = { fg = colors.variable },
    ["@variable.parameter"] = { fg = colors.variable },
    ["@variable.language"] = { fg = colors.variable },
    ["@variable.import"] = { fg = colors.variable },
    ["@variable.member.key"] = { fg = "#b15e7c" },
    ["@variable.object"] = { fg = colors.variable },
    ["@variable.constant"] = { fg = colors.constant },
    ["@constant"] = { fg = colors.constant },
    ["@constant.builtin"] = { fg = colors.keyword },
    ["@constant.macro"] = { fg = colors.keyword },
    ["@module"] = { fg = colors.keyword },
    ["@type"] = { fg = colors.number },
    ["@type.builtin"] = { fg = colors.number },
    ["@type.definition"] = { fg = colors.number },
    ["@type.qualifier"] = { fg = colors.keyword },
    ["@lsp.type.class"] = { fg = "#f43f5e" },
    ["@lsp.type.enum"] = { fg = "#f43f5e" },
    ["@attribute"] = { fg = colors.constant },
    ["@field"] = { fg = colors.variable },
    ["@namespace"] = { fg = colors.keyword },
    ["@symbol"] = { fg = colors.constant },
    ["@tag"] = { fg = colors.html_tag },
    ["@tag.attribute"] = { fg = colors.constant },
    ["@tag.delimiter"] = { fg = colors.variable },
    ["@tag.builtin"] = { fg = colors.keyword },
    ["@tag.id.css"] = { fg = colors.shebang },
    ["@tag.class.css"] = { fg = colors.constant },
    ["@tag.property.css"] = { fg = colors.variable },
    ["@tag.property-name.css"] = { fg = colors.variable },
    ["@tag.attribute.html"] = { fg = colors.constant },
    ["@tag.yaml"] = { fg = "#f43f5e" },
    ["@tag.json"] = { fg = "#d4aaff" },
    ["@property.json"] = { fg = "#d4aaff" },
    ["@tag.jsx"] = { fg = colors.jsx_component },
    ["@tag.tsx"] = { fg = colors.jsx_component },
    ["@component.jsx"] = { fg = colors.jsx_component },
    ["@component.tsx"] = { fg = colors.jsx_component },
    ["@comment"] = { fg = colors.comment, italic = true },
    ["@comment.documentation"] = { fg = colors.comment, italic = true },
    ["@comment.error"] = { fg = colors.error },
    ["@comment.warning"] = { fg = colors.warning },
    ["@comment.note"] = { fg = colors.info },
    ["@comment.todo"] = { fg = colors.warning },
    ["@comment.shebang"] = { fg = colors.shebang, italic = true },
    ["@markup.strong"] = { fg = colors.keyword, bold = true },
    ["@markup.italic"] = { fg = colors.keyword, italic = true },
    ["@markup.strikethrough"] = { fg = colors.warning, strikethrough = true },
    ["@markup.heading"] = { fg = "#cf8e6d", bold = true },
    ["@markup.heading.1"] = { fg = "#cf8e6d", bold = true },
    ["@markup.heading.2"] = { fg = "#cf8e6d", bold = true },
    ["@markup.heading.3"] = { fg = "#cf8e6d", bold = true },
    ["@markup.heading.4"] = { fg = "#cf8e6d", bold = true },
    ["@markup.heading.5"] = { fg = "#cf8e6d", bold = true },
    ["@markup.heading.6"] = { fg = "#cf8e6d", bold = true },
    ["@markup.quote"] = { fg = colors.variable },
    ["@markup.math"] = { fg = colors.keyword },
    ["@markup.link"] = { fg = "#56a8f5", underline = true },
    ["@markup.link.label"] = { fg = "#56a8f5" },
    ["@markup.link.url"] = { fg = "#56a8f5", underline = true },
    ["@markup.raw"] = { fg = "#ba8ef7" },
    ["@markup.raw.block"] = { fg = "#ba8ef7" },
    ["@markup.raw.delimiter"] = { fg = "#3c3f41" },
    ["@markup.list"] = { fg = colors.keyword },
    ["@markup.list.checked"] = { fg = colors.git_add },
    ["@markup.list.unchecked"] = { fg = colors.fg_dim },
    ["@diff.plus"] = { fg = colors.inserted },
    ["@diff.minus"] = { fg = colors.git_del },
    ["@diff.delta"] = { fg = colors.changed },
    ["@lsp.type.class"] = { fg = "#f43f5e" },
    ["@lsp.type.comment"] = { fg = colors.comment, italic = true },
    ["@lsp.type.decorator"] = { fg = "#cf8e6d" },
    ["@lsp.type.enum"] = { fg = "#f43f5e" },
    ["@lsp.type.enumMember"] = { fg = colors.constant },
    ["@lsp.type.function"] = { fg = colors.func },
    ["@lsp.type.interface"] = { fg = "#f43f5e" },
    ["@lsp.type.keyword"] = { fg = colors.keyword },
    ["@lsp.type.macro"] = { fg = "#cf8e6d" },
    ["@lsp.type.method"] = { fg = colors.func },
    ["@lsp.type.namespace"] = { fg = colors.keyword },
    ["@lsp.type.number"] = { fg = colors.number },
    ["@lsp.type.operator"] = { fg = colors.operator },
    ["@lsp.type.parameter"] = { fg = colors.variable },
    ["@lsp.type.property"] = { fg = colors.constant },
    ["@lsp.type.regexp"] = { fg = "#56adb7" },
    ["@lsp.type.string"] = { fg = colors.string },
    ["@lsp.type.struct"] = { fg = "#f43f5e" },
    ["@lsp.type.type"] = { fg = colors.number },
    ["@lsp.type.typeParameter"] = { fg = colors.number },
    ["@lsp.type.variable"] = { fg = colors.variable },
    ["@lsp.typemod.class.declaration"] = { fg = "#f43f5e" },
    ["@lsp.typemod.function.declaration"] = { fg = colors.func },
    ["@lsp.typemod.method.declaration"] = { fg = colors.func },
    ["@lsp.typemod.variable.declaration"] = { fg = colors.variable },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = colors.keyword },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = "#cf8e6d" },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = colors.number },
    ["@lsp.mod.deprecated"] = { fg = colors.warning, strikethrough = true },
    ["@lsp.mod.readonly"] = { fg = colors.constant },
    ["@lsp.type.tag"] = { fg = colors.html_tag },
    ["@lsp.type.tag.jsx"] = { fg = colors.jsx_component },
    ["@lsp.type.tag.tsx"] = { fg = colors.jsx_component },
    ["@lsp.type.property.json"] = { fg = "#d4aaff" },
    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.info },
    DiagnosticHint = { fg = colors.hint },
    DiagnosticVirtualTextError = { fg = colors.error, italic = true },
    DiagnosticVirtualTextWarn = { fg = colors.warning, italic = true },
    DiagnosticVirtualTextInfo = { fg = colors.info, italic = true },
    DiagnosticVirtualTextHint = { fg = colors.hint, italic = true },
    DiagnosticUnderlineError = { sp = colors.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.hint, undercurl = true },
    DiagnosticSignError = { fg = colors.error },
    DiagnosticSignWarn = { fg = colors.warning },
    DiagnosticSignInfo = { fg = colors.info },
    DiagnosticSignHint = { fg = colors.hint },
    LspReferenceText = { bg = "#373b39" },
    LspReferenceRead = { bg = "#373b39" },
    LspReferenceWrite = { bg = "#373b39" },
    yamlKey = { fg = "#f43f5e" },
    yamlValue = { fg = colors.string_alt },
    yamlAnchor = { fg = colors.string_alt },
    yamlAlias = { fg = colors.string_alt },
    jsonProperty = { fg = "#d4aaff" },
    jsonValue = { fg = colors.string },
    cssClassName = { fg = colors.constant },
    cssID = { fg = colors.shebang },
    cssPropertyName = { fg = colors.variable },
    cssPropertyValue = { fg = colors.constant },
    javascriptIdentifier = { fg = colors.variable },
    javascriptFunction = { fg = colors.func },
    javascriptClass = { fg = "#f43f5e" },
    typescriptIdentifier = { fg = colors.variable },
    typescriptFunction = { fg = colors.func },
    typescriptClass = { fg = "#f43f5e" },
    jsxComponentName = { fg = colors.jsx_component },
    jsxTagName = { fg = colors.html_tag },
    tsxComponentName = { fg = colors.jsx_component },
    tsxTagName = { fg = colors.html_tag },
    LspCodeLens = { fg = colors.fg_dim },
    LspCodeLensSeparator = { fg = colors.fg_dim },
    LspInlayHint = { fg = colors.hint, bg = M.options.transparent and "none" or "#3c3f41" },
    LspSignatureActiveParameter = { fg = colors.variable, bold = true },
    GitSignsAdd = { fg = colors.git_add },
    GitSignsChange = { fg = colors.git_mod },
    GitSignsDelete = { fg = colors.git_del },
    GitSignsAddLn = { bg = "#252629" },
    GitSignsChangeLn = { bg = "#252629" },
    GitSignsDeleteLn = { bg = "#252629" },
    GitSignsAddPreview = { bg = "#252629" },
    GitSignsDeletePreview = { bg = "#252629" },
    GitSignsCurrentLineBlame = { fg = colors.fg_dim, italic = true },
    TelescopeNormal = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    TelescopeBorder = { fg = "#3c3f41" },
    TelescopeTitle = { fg = colors.fg },
    TelescopePromptPrefix = { fg = colors.keyword },
    TelescopePromptNormal = { fg = colors.fg },
    TelescopePromptCounter = { fg = colors.fg_dim },
    TelescopeSelection = { fg = "#bcbec4", bg = "#25324d" },
    TelescopeSelectionCaret = { fg = colors.keyword },
    TelescopeMultiSelection = { fg = colors.keyword },
    TelescopeMatching = { fg = colors.search_match, bold = true },
    TelescopePreviewLine = { bg = colors.line_highlight },
    TelescopePreviewMatch = { fg = colors.search_match, bold = true },
    TelescopePreviewPipe = { fg = colors.constant },
    TelescopePreviewCharDev = { fg = colors.git_del },
    TelescopePreviewDirectory = { fg = colors.directory },
    TelescopePreviewBlock = { fg = colors.warning },
    TelescopePreviewLink = { fg = colors.search_match, underline = true },
    TelescopePreviewSocket = { fg = colors.string },
    TelescopePreviewRead = { fg = colors.git_add },
    TelescopePreviewWrite = { fg = colors.git_mod },
    TelescopePreviewExecute = { fg = colors.func },
    TelescopePreviewSticky = { fg = colors.keyword },
    TelescopePreviewSize = { fg = colors.number },
    TelescopePreviewUser = { fg = colors.constant },
    TelescopePreviewGroup = { fg = colors.constant },
    TelescopePreviewDate = { fg = colors.variable },
    TelescopePreviewMessage = { fg = colors.comment },
    TelescopePreviewMessageFillchar = { fg = colors.comment },
    TreesitterContext = { bg = colors.line_highlight },
    TreesitterContextLineNumber = { fg = "#4e5157" },
    IndentBlanklineChar = { fg = "#3c3f41", nocombine = true },
    IndentBlanklineContextChar = { fg = colors.keyword, nocombine = true },
    IndentBlanklineContextStart = { bg = "#252629" },
    IndentBlanklineSpaceChar = { fg = "#3c3f41", nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = "#3c3f41", nocombine = true },
    IblIndent = { fg = "#3c3f41", nocombine = true },
    IblScope = { fg = colors.keyword, nocombine = true },
    CmpItemAbbr = { fg = colors.fg },
    CmpItemAbbrDeprecated = { fg = colors.fg_dim, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.search_match, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = colors.search_match, bold = true },
    CmpItemMenu = { fg = colors.fg_dim },
    CmpItemKindText = { fg = colors.fg },
    CmpItemKindMethod = { fg = colors.func },
    CmpItemKindFunction = { fg = colors.func },
    CmpItemKindConstructor = { fg = "#ba8ef7" },
    CmpItemKindField = { fg = colors.constant },
    CmpItemKindVariable = { fg = colors.variable },
    CmpItemKindClass = { fg = "#f43f5e" },
    CmpItemKindInterface = { fg = "#f43f5e" },
    CmpItemKindModule = { fg = colors.keyword },
    CmpItemKindProperty = { fg = colors.constant },
    CmpItemKindUnit = { fg = colors.constant },
    CmpItemKindValue = { fg = colors.constant },
    CmpItemKindEnum = { fg = "#f43f5e" },
    CmpItemKindKeyword = { fg = colors.keyword },
    CmpItemKindSnippet = { fg = colors.keyword },
    CmpItemKindColor = { fg = colors.constant },
    CmpItemKindFile = { fg = colors.keyword },
    CmpItemKindReference = { fg = colors.constant },
    CmpItemKindFolder = { fg = colors.directory },
    CmpItemKindEnumMember = { fg = colors.constant },
    CmpItemKindConstant = { fg = colors.constant },
    CmpItemKindStruct = { fg = "#f43f5e" },
    CmpItemKindEvent = { fg = colors.warning },
    CmpItemKindOperator = { fg = colors.operator },
    CmpItemKindTypeParameter = { fg = colors.number },
    CmpItemKindJSON = { fg = "#d4aaff" },
    CmpItemKindCSS = { fg = colors.variable },
    CmpItemKindJSX = { fg = colors.jsx_component },
    CmpItemKindTSX = { fg = colors.jsx_component },
    NeoTreeNormal = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    NeoTreeNormalNC = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    NeoTreeCursorLine = { bg = "#252629" },
    NeoTreeDimText = { fg = colors.fg_dim },
    NeoTreeDirectoryIcon = { fg = colors.directory },
    NeoTreeDirectoryName = { fg = colors.fg },
    NeoTreeRootName = { fg = colors.keyword, bold = true },
    NeoTreeGitAdded = { fg = colors.git_add },
    NeoTreeGitConflict = { fg = colors.warning },
    NeoTreeGitDeleted = { fg = colors.git_del },
    NeoTreeGitIgnored = { fg = colors.fg_dim },
    NeoTreeGitModified = { fg = colors.git_mod },
    NeoTreeGitRenamed = { fg = colors.directory },
    NeoTreeGitUntracked = { fg = colors.git_add },
    NeoTreeIndentMarker = { fg = "#3c3f41" },
    NeoTreeExpander = { fg = colors.fg_dim },
    NeoTreeModified = { fg = colors.git_mod },
    NeoTreeFloatTitle = { fg = colors.fg },
    NeoTreeFloatBorder = { fg = "#3c3f41" },
    WhichKeyNormal = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    WhichKeyBorder = { fg = "#3c3f41" },
    WhichKeyGroup = { fg = colors.keyword },
    WhichKeySeparator = { fg = colors.fg_dim },
    WhichKeyDesc = { fg = colors.fg },
    WhichKeyFloating = { fg = colors.fg, bg = M.options.transparent and "none" or colors.float_bg },
    WhichKeyValue = { fg = colors.fg_dim },
    FlashBackdrop = { fg = colors.fg_dim },
    FlashLabel = { fg = colors.bg, bg = colors.keyword, bold = true },
    FlashMatch = { bg = colors.search_match, fg = colors.bg },
    FlashCurrent = { bg = colors.search_match, fg = colors.bg },
    NoiceCmdlinePopup = { fg = colors.fg, bg = M.options.transparent and "none" or colors.float_bg },
    NoiceCmdlinePopupBorder = { fg = "#3c3f41" },
    NoiceCmdlinePopupTitle = { fg = colors.keyword },
    NoiceCmdlineIcon = { fg = colors.keyword },
    NoiceConfirm = { fg = colors.fg, bg = M.options.transparent and "none" or colors.float_bg },
    NoiceConfirmBorder = { fg = "#3c3f41" },
    NoiceFormatTitle = { fg = colors.keyword },
    NoiceFormatProgressDone = { fg = colors.git_add },
    NoiceFormatProgressTodo = { fg = colors.fg_dim },
    NoiceMini = { fg = colors.fg, bg = M.options.transparent and "none" or colors.float_bg },
    NotifyBackground = { bg = M.options.transparent and "none" or colors.bg },
    NotifyERRORBorder = { fg = colors.error },
    NotifyWARNBorder = { fg = colors.warning },
    NotifyINFOBorder = { fg = colors.info },
    NotifyDEBUGBorder = { fg = colors.fg_dim },
    NotifyTRACEBorder = { fg = colors.keyword },
    NotifyERRORIcon = { fg = colors.error },
    NotifyWARNIcon = { fg = colors.warning },
    NotifyINFOIcon = { fg = colors.info },
    NotifyDEBUGIcon = { fg = colors.fg_dim },
    NotifyTRACEIcon = { fg = colors.keyword },
    NotifyERRORTitle = { fg = colors.error },
    NotifyWARNTitle = { fg = colors.warning },
    NotifyINFOTitle = { fg = colors.info },
    NotifyDEBUGTitle = { fg = colors.fg_dim },
    NotifyTRACETitle = { fg = colors.keyword },
    NotifyERRORBody = { fg = colors.fg },
    NotifyWARNBody = { fg = colors.fg },
    NotifyINFOBody = { fg = colors.fg },
    NotifyDEBUGBody = { fg = colors.fg },
    NotifyTRACEBody = { fg = colors.fg },
    MasonNormal = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    MasonHeader = { fg = colors.bg, bg = colors.keyword, bold = true },
    MasonHeaderSecondary = { fg = colors.bg, bg = colors.info, bold = true },
    MasonHighlight = { fg = colors.keyword },
    MasonHighlightBlock = { fg = colors.bg, bg = colors.keyword },
    MasonHighlightBlockBold = { fg = colors.bg, bg = colors.keyword, bold = true },
    MasonHighlightSecondary = { fg = colors.info },
    MasonHighlightBlockSecondary = { fg = colors.bg, bg = colors.info },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg, bg = colors.info, bold = true },
    MasonMuted = { fg = colors.fg_dim },
    MasonMutedBlock = { fg = colors.bg, bg = colors.fg_dim },
    MasonMutedBlockBold = { fg = colors.bg, bg = colors.fg_dim, bold = true },
    MasonHeading = { fg = colors.fg, bold = true },
    LspInfoBorder = { fg = "#3c3f41" },
    LspInfoList = { fg = colors.fg },
    LspInfoTip = { fg = colors.info },
    LspInfoTitle = { fg = colors.keyword },
    LspInfoFiletype = { fg = colors.func },
    BufferLineTab = { fg = colors.fg_dim, bg = colors.bg_alt },
    BufferLineTabSelected = { fg = colors.fg, bg = M.options.transparent and "none" or colors.bg },
    BufferLineTabClose = { fg = colors.git_del },
    BufferLineIndicatorSelected = { fg = colors.info },
    DashboardHeader = { fg = colors.keyword },
    DashboardFooter = { fg = colors.git_add },
    DashboardShortcut = { fg = colors.git_del },
    DashboardIcon = { fg = colors.info },
    DashboardDesc = { fg = colors.fg },
    DashboardKey = { fg = colors.keyword },
    DashboardProjectTitle = { fg = colors.keyword },
    DashboardProjectTitleIcon = { fg = colors.info },
    DashboardProjectMtime = { fg = colors.fg_dim },
    DashboardFilesMtime = { fg = colors.fg_dim },
    AlphaHeader = { fg = colors.keyword },
    AlphaButtons = { fg = colors.fg },
    AlphaShortcut = { fg = colors.keyword },
    AlphaFooter = { fg = colors.git_add },
  }

  for group, hl in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, hl)
  end

  vim.g.terminal_color_0 = "#191a1c"
  vim.g.terminal_color_1 = "#ff6b66"
  vim.g.terminal_color_2 = "#8ed16a"
  vim.g.terminal_color_3 = "#ffb347"
  vim.g.terminal_color_4 = "#6699ff"
  vim.g.terminal_color_5 = "#d4aaff"
  vim.g.terminal_color_6 = "#4dd0e1"
  vim.g.terminal_color_7 = "#e0e2e8"
  vim.g.terminal_color_8 = "#7a7e85"
  vim.g.terminal_color_9 = "#ff8a85"
  vim.g.terminal_color_10 = "#a3e635"
  vim.g.terminal_color_11 = "#ffd966"
  vim.g.terminal_color_12 = "#9bc4ff"
  vim.g.terminal_color_13 = "#e8b4ff"
  vim.g.terminal_color_14 = "#70d4e8"
  vim.g.terminal_color_15 = "#ffffff"
end

return M
